// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFGetStarted.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20241031105059_author, contacts, address etc")]
    partial class authorcontactsaddressetc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BlogId"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("BlogId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.OwnsOne("ContactDetails", "Contact", b1 =>
                        {
                            b1.Property<int>("AuthorId")
                                .HasColumnType("integer");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.HasKey("AuthorId");

                            b1.ToTable("Author");

                            b1.ToJson("Contact");

                            b1.WithOwner()
                                .HasForeignKey("AuthorId");

                            b1.OwnsOne("Address", "Address", b2 =>
                                {
                                    b2.Property<int>("ContactDetailsAuthorId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Postcode")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("ContactDetailsAuthorId");

                                    b2.ToTable("Author");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactDetailsAuthorId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.HasOne("Author", null)
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId");

                    b.HasOne("Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PostMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("PostId")
                                .HasColumnType("integer");

                            b1.Property<int>("Views")
                                .HasColumnType("integer");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.ToJson("Metadata");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.OwnsMany("PostUpdate", "Updates", b2 =>
                                {
                                    b2.Property<int>("PostMetadataPostId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<IPAddress>("PostedFrom")
                                        .IsRequired()
                                        .HasColumnType("inet");

                                    b2.Property<string>("UpdatedBy")
                                        .HasColumnType("text");

                                    b2.Property<DateTime>("UpdatedOn")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("PostMetadataPostId", "Id");

                                    b2.ToTable("Posts");

                                    b2.WithOwner()
                                        .HasForeignKey("PostMetadataPostId");

                                    b2.OwnsMany("Commit", "Commits", b3 =>
                                        {
                                            b3.Property<int>("PostUpdatePostMetadataPostId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("PostUpdateId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<string>("Comment")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<DateTime>("CommittedOn")
                                                .HasColumnType("timestamp with time zone");

                                            b3.HasKey("PostUpdatePostMetadataPostId", "PostUpdateId", "Id");

                                            b3.ToTable("Posts");

                                            b3.WithOwner()
                                                .HasForeignKey("PostUpdatePostMetadataPostId", "PostUpdateId");
                                        });

                                    b2.Navigation("Commits");
                                });

                            b1.OwnsMany("SearchTerm", "TopSearches", b2 =>
                                {
                                    b2.Property<int>("PostMetadataPostId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("Count")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Term")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("PostMetadataPostId", "Id");

                                    b2.ToTable("Posts");

                                    b2.WithOwner()
                                        .HasForeignKey("PostMetadataPostId");
                                });

                            b1.OwnsMany("Visits", "TopGeographies", b2 =>
                                {
                                    b2.Property<int>("PostMetadataPostId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<List<string>>("Browsers")
                                        .HasColumnType("text[]");

                                    b2.Property<int>("Count")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("PostMetadataPostId", "Id");

                                    b2.ToTable("Posts");

                                    b2.WithOwner()
                                        .HasForeignKey("PostMetadataPostId");
                                });

                            b1.Navigation("TopGeographies");

                            b1.Navigation("TopSearches");

                            b1.Navigation("Updates");
                        });

                    b.Navigation("Blog");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Blog", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
